### ISSUE TITLE
Question about the training code for content diffusion model

### ISSUE THREAD

**Issue by Dorniwang** [NVlabs/CMD#2]
Hi Sihyun,

This is an amazing work to me! 

I have a question about your content diffusion model training code. It seems like no pretrained image diffusion model is used during your training? The code seems like train the content diffision model from scratch. Am I right?

**Comment by sihyun-yu** [comment]
Hi, the current codebase is based on pixel-level autoencoder and diffusion models on UCF-101, in which we do not use any pretrained models. But we fine-tuned stable-diffusion for content diffusion in t2v experiments and you can definitiely follow this strategy as well.
